### ISSUE TITLE
package-buffer-info: Package lacks a "Version" or "Package-Version" header

### ISSUE THREAD

**Issue by subnut** [amno1/org-babel-hide-markers-mode#3]
When <kbd>M-x</kbd> `package-install-file` <kbd>RET</kbd> `ob-hide-markers.el` <kbd>RET</kbd>

**Comment by amno1** [comment]
True indeed. I didn't meant this to be installed as a package, since I don't think it is a "package quality" to be honest. It was more just an experimental hack. There are problems with it that I haven't solved, for example there is popping of src_block markers, which I am not sure why. I believe due to synergy (or lack of) between font-lock and org-mode. Another issue is that it can be tricky to enter src_blocks when this mode is enabled, since it works on very "wide" regex, if you check hbm--marker-re. That one is easily fixed though, but fixing the popping probably requires a bit more work.

I have added now a version so it is installable with package.el: M-x package-install-file should work.

**Comment by amno1** [comment]
As a note if you plan to use this, I have now refactored code and updates, now it should compile without byte-compiler warnings. 

When tested with my init file now I don't see that annoying popping of markers any more. Maybe it was a bug in org-mode that caused it before. I can't tell. But actually seems to work now.

**Comment by subnut** [comment]
Thanks! Will check again and report if any issues crop up.

Closing for now.
